Exercise 31:

Create a DataFrame with random values.

In [2]:
import pandas as pd 
import numpy as np 

data=np.random.rand(4,3)
df=pd.DataFrame(data)
print(data)


[[1.49761403e-01 1.63680452e-04 8.61690732e-01]
 [3.19365791e-01 5.22676472e-01 1.28275941e-02]
 [7.65445973e-01 3.68272995e-01 8.70058440e-01]
 [4.79172100e-01 8.98810672e-01 8.11185314e-01]]


Exercise 32:

Calculate the rank of values in a DataFrame.

In [3]:
import pandas as pd
data = {'X': [3, 1, 4, 1], 'Y': [2, 3, 1, 4]}
df = pd.DataFrame(data)
df['Rank'] = df['X'].rank()
print(df)

   X  Y  Rank
0  3  2   3.0
1  1  3   1.5
2  4  1   4.0
3  1  4   1.5


Exercise 33:

Change the data type of a column.

In [4]:
import pandas as pd 
data = {'X': ['1', '2', '3']}
df= pd.DataFrame(data)
df['X']=df['X'].astype(int)

print (df)

   X
0  1
1  2
2  3


Exercise 34:

Filter rows based on string matching.

In [ ]:
import pandas as pd 
data = {'X': ['foo', 'bar', 'baz', 'qux']}
df = pd.DataFrame(data)
filtro_df=df[df['X'].str.contains('ba')]
print(filtro_df)