Exercise 31:

Create a DataFrame with random values.

In [2]:
import pandas as pd 
import numpy as np 

data=np.random.rand(4,3)
df=pd.DataFrame(data)
print(data)


[[1.49761403e-01 1.63680452e-04 8.61690732e-01]
 [3.19365791e-01 5.22676472e-01 1.28275941e-02]
 [7.65445973e-01 3.68272995e-01 8.70058440e-01]
 [4.79172100e-01 8.98810672e-01 8.11185314e-01]]


Exercise 32:

Calculate the rank of values in a DataFrame.

In [3]:
import pandas as pd
data = {'X': [3, 1, 4, 1], 'Y': [2, 3, 1, 4]}
df = pd.DataFrame(data)
df['Rank'] = df['X'].rank()
print(df)

   X  Y  Rank
0  3  2   3.0
1  1  3   1.5
2  4  1   4.0
3  1  4   1.5


Exercise 33:

Change the data type of a column.

In [4]:
import pandas as pd 
data = {'X': ['1', '2', '3']}
df= pd.DataFrame(data)
df['X']=df['X'].astype(int)

print (df)

   X
0  1
1  2
2  3


Exercise 34:

Filter rows based on string matching.

In [5]:
import pandas as pd 
data = {'X': ['foo', 'bar', 'baz', 'qux']}
df = pd.DataFrame(data)
filtro_df=df[df['X'].str.contains('ba')]
print(filtro_df)

     X
1  bar
2  baz


Exercise 35:

Create a DataFrame with specified row and column labels.

In [6]:
import pandas as pd
data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
df = pd.DataFrame(data, index=['row1', 'row2', 'row3'], columns=['col1', 'col2', 'col3'])
print(df)

      col1  col2  col3
row1     1     2     3
row2     4     5     6
row3     7     8     9


Exercise 36:

Transpose a DataFrame.

In [7]:
import pandas as pd
data = {'X': [1, 2, 3], 'Y': [4, 5, 6]}
df = pd.DataFrame(data)
transposed_df = df.T
print(transposed_df)

   0  1  2
X  1  2  3
Y  4  5  6


Exercise 37:

Set a column as the index of a DataFrame.

In [9]:
import pandas as pd
data = {'X': [1, 2, 3], 'Y': [4, 5, 6]}
df = pd.DataFrame(data)
print(df)
df.set_index('X', inplace=True)
print(df)

   X  Y
0  1  4
1  2  5
2  3  6
   Y
X   
1  4
2  5
3  6


Exercise 38:

Reset the index of a DataFrame.

In [10]:
import pandas as pd
data = {'X': [1, 2, 3], 'Y': [4, 5, 6]}
df = pd.DataFrame(data)
df.set_index('X', inplace=True)
df.reset_index(inplace=True)
print(df)

   X  Y
0  1  4
1  2  5
2  3  6


Exercise 39:

Add a prefix or suffix to column names.

In [11]:
import pandas as pd
data = {'X': [1, 2, 3], 'Y': [4, 5, 6]}
df = pd.DataFrame(data)
df = df.add_prefix('col_')
print(df)

   col_X  col_Y
0      1      4
1      2      5
2      3      6


Exercise 40:

Filter rows based on datetime index.

In [12]:
import pandas as pd
date_range = pd.date_range(start='1/1/2020', periods=5, freq='D')
data = {'X': [1, 2, 3, 4, 5]}
df = pd.DataFrame(data, index=date_range)
filtered_df = df['2020-01-03':'2020-01-05']
print(filtered_df)

            X
2020-01-03  3
2020-01-04  4
2020-01-05  5
